### ISSUE TITLE
Add a new Docker script

### ISSUE THREAD

**Issue by davidgatti** [0x4447/0x4447_docker#8]
I'd like to have this command `docker rm $(docker ps -a -q)` to be added to the Dockerfile, but as a separated command, this way it is going to be easier to track when more commands will be added.

**Comment by ScriptMyJob** [comment]
David,

Sorry, you can't run `docker` commands in a Dockerfile (unless you are using a DinD image).  Do you want me instead to update the README on how you can clean up images on your system?

Let me know what you would like to do.

Respectfully,
Robert J.

**Comment by davidgatti** [comment]
🤣🤣🤣 super stupid me, and yes, lets just update the Readme :)

**Comment by ScriptMyJob** [comment]
PR #12 has been updated with this documentation request.
