### ISSUE TITLE
Make NodeJS be the latest version?

### ISSUE THREAD

**Issue by davidgatti** [0x4447/0x4447_docker#9]
Not sure if this is possible. But it be cool if rebuild the docker image would actually run the NVM command from scratch each time so when you rebuild you get the latest version of NodeJS and NPM.

**Comment by ScriptMyJob** [comment]
I think that the best way to mitigate this would be to do a `docker builder prune` after deleting the docker images (This will remove the cached layers associated with said docker images). 

An easier thing to do would be to just do a `docker system prune -af`.

**Comment by davidgatti** [comment]
is it possible for example to set not to cash a layer/step?

**Comment by ScriptMyJob** [comment]
I added the `--no-cache` build option to the README and this change is in PR #12.
